---
- include: etc_hosts.yml

- hosts: ansiblesetup
  become: true
  vars:
    use_bundle: true
    postgres_streaming_replication: true
    ansible_tower_version: 3.2.1-1.el7
  roles:
    - role: setup-tower
    - role: network_routes
    - role: fetch_ssh_key
