---
- include: etc_hosts.yml

- hosts: all
  become: true
  vars:
    dns_domain: test.local
    net_path: "/etc/sysconfig/network-scripts/"

  roles:
    - role: prep-tower-server
    - role: network_routes
      when: network_interfaces is defined
    - role: firewall
      when: iptables_rules is defined

