---
- include: etc_hosts.yml

- hosts: all
  become: true
  vars:
    dns_domain: test.local
  tasks:
    - name: update all packages
      yum: name='*' state=latest

    - name: install some core packages
      yum: name="{{item}}" update_cache=yes
      with_items:
        - vim-enhanced
        - libselinux-python


    - name: set hostname
      hostname: name="{{ inventory_hostname}}.{{ dns_domain }}"
    - name: ensure selinux is set to enforcing
      selinux:
        policy: targeted
        state: enforcing

    # Tower install does it as root , not as a sudo user
    # so install the key into the root account
    - name: update authorized files
      authorized_key:
        user: root
        key:  "{{ lookup('file', './ansiblesetup.pub.key') }}"
