---
- hosts: all
  become: true
  pre_tasks:
    - name: convert ruby formatted hostlist to ansible host_additional_host yaml format"
      set_fact:
        etc_hosts: "{{ lookup('template', 'etc_hosts.j2') | from_yaml }} "
  roles:
    - role: ansible-role-hosts
      hosts_additional_hosts: "{{ etc_hosts }}"
