---
- hosts: all
  become: true
  roles:
    - role: ansible-role-hosts
      hosts_additional_hosts:
        - address: 10.1.1.4
          hostnames:
            - tower1
        - address: 10.1.1.3
          hostnames:
            - postgres1
        - address: 10.1.4.10
          hostnames:
            - tower2
        - address: 10.1.3.10
          hostnames:
            - tower3
