- name: "create ssh key for {{ ansible_user_id }}"
  user: name="{{ ansible_user_id }}" generate_ssh_key=yes

- name: fetch the ssh key, place it on the hypervisor. call the file ansiblesetup.pub.key
  fetch:
    src: "{{ ansible_user_dir}}/.ssh/id_rsa.pub"
    dest: ./ansiblesetup.pub.key
    flat: yes
