net_path: "/etc/sysconfig/network-scripts/"
network_interfaces:
  - device: eth3
    route:
      - network: 10.1.3.0
        netmask: 255.255.255.0
        gateway: 10.1.2.3

      - network: 10.1.5.0
        netmask: 255.255.255.0
        gateway: 10.1.2.3
